# Generated by Django 6.0.6 on 2026-06-21 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='imaage',
            new_name='image',
        ),
    ]
